version: '3'

services:
  rabbitmq: 
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
